SELECT 
 S.SYSTEMSTUDENTID STUDENT_NUMBER
,SCH.ABBREVIATION
,AR.MASTERY AR_MASTERY
,AR.DATE 'AR AS OF'
,AM.MASTERY AM_MASTERY
,AM.DATE 'AM AS OF'
,MAP_MATH.MATH_RIT_SCORE
,MAP_MATH.MATH_PERC_SCORE
,MAP_MATH.MATH_TEST_DATE 'MAP MATH AS OF'
,MAP_READ.READ_RIT_SCORE
,MAP_READ.READ_PERC_SCORE
,MAP_READ.READ_TEST_DATE 'MAP READ AS OF'
,ANET_MATH.ANET_PERC_SCORE
,ANET_MATH.MATH_TEST_DATE 'ANET MATH AS OF'
,ANET_READ.ANET_PERC_SCORE
,ANET_READ.READ_TEST_DATE 'ANET READ AS OF'
FROM DW.DW_DIMSTUDENT S
JOIN [custom].[custom_StudentBridge] SB ON SB.SYSTEMSTUDENTID = S.SYSTEMSTUDENTID
JOIN POWERSCHOOL.POWERSCHOOL_STUDENTS PS ON PS.STUDENT_NUMBER = SB.STUDENT_NUMBER
JOIN POWERSCHOOL.POWERSCHOOL_SCHOOLS SCH ON SCH.SCHOOL_NUMBER = PS.SCHOOLID AND SCH.ABBREVIATION IN ('NE','Valor','AIM','Heights','WILL')
LEFT JOIN
	(SELECT
	 SYSTEMSTUDENTID
	,MASTERY
	,DATE
	,RANK() OVER (PARTITION BY SYSTEMSTUDENTID ORDER BY SYSTEMSTUDENTID, DATE DESC) AR_RANK
	FROM CUSTOM.INSTRUCTION_BLENDED_FACT F
	JOIN DW.DW_DIMSTUDENT S ON S.STUDENTKEY = F.STUDENTKEY
	WHERE PLATFORMKEY = 6
	AND F.DATE<CONVERT(DATE,GETDATE())
	AND F.DATE >= '2016-08-01'
	) AR ON AR.SYSTEMSTUDENTID = S.SYSTEMSTUDENTID AND AR_RANK = 1
LEFT JOIN
	(SELECT
	 SYSTEMSTUDENTID
	,MASTERY
	,DATE
	,RANK() OVER (PARTITION BY SYSTEMSTUDENTID ORDER BY SYSTEMSTUDENTID, DATE DESC) AM_RANK
	FROM CUSTOM.INSTRUCTION_BLENDED_FACT F
	JOIN DW.DW_DIMSTUDENT S ON S.STUDENTKEY = F.STUDENTKEY
	WHERE PLATFORMKEY = 7
	AND F.DATE<CONVERT(DATE,GETDATE())
	AND F.DATE >= '2016-08-01'
	) AM ON AM.SYSTEMSTUDENTID = S.SYSTEMSTUDENTID AND AM_RANK = 1
LEFT JOIN (
	SELECT
	DIM_S.SYSTEMSTUDENTID STUDENTID
	,F.SCALESCORE MATH_RIT_SCORE
	,F.PERCENTILESCORE MATH_PERC_SCORE
	,DIM_CAL.FULLDATE MATH_TEST_DATE
	,DIM_S.GRADELEVEL
	,RANK() OVER (PARTITION BY  DIM_S.SYSTEMSTUDENTID,TESTSUBJECT ORDER BY DIM_S.SYSTEMSTUDENTID,TESTSUBJECT,FULLDATE DESC) RECORD_RANK
	FROM [DW].[DW_FACTTESTSCORES] F
		LEFT JOIN [DW].[DW_DIMSCHOOLCALENDAR] DIM_CAL ON (F.[SCHOOLCALENDARKEY] = DIM_CAL.[SCHOOLCALENDARKEY])
		LEFT JOIN [DW].[DW_DIMSTUDENT] DIM_S ON (F.[STUDENTKEY] = DIM_S.[STUDENTKEY])
		LEFT JOIN [DW].[DW_DIMSTUDENTHISTORICAL] DIM_SH ON F.STUDENTHISTORICALKEY = DIM_SH.STUDENTHISTORICALKEY
		LEFT JOIN [DW].[DW_DIMSCHOOL] DIM_SCH ON F.SCHOOLKEY = DIM_SCH.SCHOOLKEY
		LEFT JOIN [DW].[DW_DIMTEST] DIM_TEST ON (F.[TESTKEY] = DIM_TEST.[TESTKEY])
		LEFT JOIN [DW].[DW_DIMTESTFRAMEWORK] DIM_TF ON (F.[TESTFRAMEWORKKEY] = DIM_TF.[TESTFRAMEWORKKEY])
		LEFT JOIN [DW].[DW_DIMTESTPROFICIENCYLEVEL] [DW_DIMTESTPROFICIENCYLEVEL] ON (F.[TESTPROFICIENCYLEVELKEY] = [DW_DIMTESTPROFICIENCYLEVEL].[TESTPROFICIENCYLEVELKEY])
	WHERE TESTTYPE = 'NWEA MAP'
	AND TESTSCORETYPE = 'Test'
	--and schoolname_abbreviation = 'NE'
	--AND DIM_S.ENROLLMENTSTATUS = 'Currently Enrolled'
	AND TESTSUBJECT = 'Mathematics'
	) MAP_MATH ON MAP_MATH.STUDENTID = S.SYSTEMSTUDENTID AND MAP_MATH.RECORD_RANK = 1
LEFT JOIN (
	SELECT
	DIM_S.SYSTEMSTUDENTID STUDENTID
	,F.SCALESCORE READ_RIT_SCORE
	,F.PERCENTILESCORE READ_PERC_SCORE
	,DIM_CAL.FULLDATE READ_TEST_DATE
	,DIM_S.GRADELEVEL
	,SCHOOLNAME_ABBREVIATION
	,RANK() OVER (PARTITION BY  DIM_S.SYSTEMSTUDENTID,TESTSUBJECT ORDER BY DIM_S.SYSTEMSTUDENTID,TESTSUBJECT,FULLDATE DESC) RECORD_RANK
	FROM [DW].[DW_FACTTESTSCORES] F
		LEFT JOIN [DW].[DW_DIMSCHOOLCALENDAR] DIM_CAL ON (F.[SCHOOLCALENDARKEY] = DIM_CAL.[SCHOOLCALENDARKEY])
		LEFT JOIN [DW].[DW_DIMSTUDENT] DIM_S ON (F.[STUDENTKEY] = DIM_S.[STUDENTKEY])
		LEFT JOIN [DW].[DW_DIMSTUDENTHISTORICAL] DIM_SH ON F.STUDENTHISTORICALKEY = DIM_SH.STUDENTHISTORICALKEY
		LEFT JOIN [DW].[DW_DIMSCHOOL] DIM_SCH ON F.SCHOOLKEY = DIM_SCH.SCHOOLKEY
		LEFT JOIN [DW].[DW_DIMTEST] DIM_TEST ON (F.[TESTKEY] = DIM_TEST.[TESTKEY])
		LEFT JOIN [DW].[DW_DIMTESTFRAMEWORK] DIM_TF ON (F.[TESTFRAMEWORKKEY] = DIM_TF.[TESTFRAMEWORKKEY])
		LEFT JOIN [DW].[DW_DIMTESTPROFICIENCYLEVEL] [DW_DIMTESTPROFICIENCYLEVEL] ON (F.[TESTPROFICIENCYLEVELKEY] = [DW_DIMTESTPROFICIENCYLEVEL].[TESTPROFICIENCYLEVELKEY])
	WHERE TESTTYPE = 'NWEA MAP'
	AND TESTSCORETYPE = 'Test'
	--AND SCHOOLNAME_ABBREVIATION in ('NE','Valor')
	--AND DIM_S.ENROLLMENTSTATUS = 'Currently Enrolled'
	AND TESTSUBJECT = 'Reading'
	) MAP_READ ON MAP_READ.STUDENTID = S.SYSTEMSTUDENTID AND MAP_READ.RECORD_RANK = 1
LEFT JOIN (
	SELECT
	DIM_S.SYSTEMSTUDENTID STUDENTID
	,F.RAWSCORE ANET_RAW_SCORE
	,F.PERCENTSCORE ANET_PERC_SCORE
	,DIM_CAL.FULLDATE MATH_TEST_DATE
	,DIM_S.GRADELEVEL
	,testscoretype
	,RANK() OVER (PARTITION BY  DIM_S.SYSTEMSTUDENTID,TESTSUBJECT ORDER BY DIM_S.SYSTEMSTUDENTID,TESTSUBJECT,FULLDATE DESC) RECORD_RANK
	FROM [DW].[DW_FACTTESTSCORES] F
		LEFT JOIN [DW].[DW_DIMSCHOOLCALENDAR] DIM_CAL ON (F.[SCHOOLCALENDARKEY] = DIM_CAL.[SCHOOLCALENDARKEY])
		LEFT JOIN [DW].[DW_DIMSTUDENT] DIM_S ON (F.[STUDENTKEY] = DIM_S.[STUDENTKEY])
		LEFT JOIN [DW].[DW_DIMSTUDENTHISTORICAL] DIM_SH ON F.STUDENTHISTORICALKEY = DIM_SH.STUDENTHISTORICALKEY
		LEFT JOIN [DW].[DW_DIMSCHOOL] DIM_SCH ON F.SCHOOLKEY = DIM_SCH.SCHOOLKEY
		LEFT JOIN [DW].[DW_DIMTEST] DIM_TEST ON (F.[TESTKEY] = DIM_TEST.[TESTKEY])
		LEFT JOIN [DW].[DW_DIMTESTFRAMEWORK] DIM_TF ON (F.[TESTFRAMEWORKKEY] = DIM_TF.[TESTFRAMEWORKKEY])
		LEFT JOIN [DW].[DW_DIMTESTPROFICIENCYLEVEL] [DW_DIMTESTPROFICIENCYLEVEL] ON (F.[TESTPROFICIENCYLEVELKEY] = [DW_DIMTESTPROFICIENCYLEVEL].[TESTPROFICIENCYLEVELKEY])
	WHERE TESTTYPE = 'Test_ANet'
	AND TESTSCORETYPE = 'Test'
	--and schoolname_abbreviation = 'NE'
	--AND DIM_S.ENROLLMENTSTATUS = 'Currently Enrolled'
	AND TESTSUBJECT = 'Mathematics') ANET_MATH ON ANET_MATH.STUDENTID = S.SYSTEMSTUDENTID AND ANET_MATH.RECORD_RANK = 1
LEFT JOIN (
	SELECT
	DIM_S.SYSTEMSTUDENTID STUDENTID
	,F.RAWSCORE ANET_RAW_SCORE
	,F.PERCENTSCORE ANET_PERC_SCORE
	,DIM_CAL.FULLDATE READ_TEST_DATE
	,DIM_S.GRADELEVEL
	,testscoretype
	,RANK() OVER (PARTITION BY  DIM_S.SYSTEMSTUDENTID,TESTSUBJECT ORDER BY DIM_S.SYSTEMSTUDENTID,TESTSUBJECT,FULLDATE DESC) RECORD_RANK
	FROM [DW].[DW_FACTTESTSCORES] F
		LEFT JOIN [DW].[DW_DIMSCHOOLCALENDAR] DIM_CAL ON (F.[SCHOOLCALENDARKEY] = DIM_CAL.[SCHOOLCALENDARKEY])
		LEFT JOIN [DW].[DW_DIMSTUDENT] DIM_S ON (F.[STUDENTKEY] = DIM_S.[STUDENTKEY])
		LEFT JOIN [DW].[DW_DIMSTUDENTHISTORICAL] DIM_SH ON F.STUDENTHISTORICALKEY = DIM_SH.STUDENTHISTORICALKEY
		LEFT JOIN [DW].[DW_DIMSCHOOL] DIM_SCH ON F.SCHOOLKEY = DIM_SCH.SCHOOLKEY
		LEFT JOIN [DW].[DW_DIMTEST] DIM_TEST ON (F.[TESTKEY] = DIM_TEST.[TESTKEY])
		LEFT JOIN [DW].[DW_DIMTESTFRAMEWORK] DIM_TF ON (F.[TESTFRAMEWORKKEY] = DIM_TF.[TESTFRAMEWORKKEY])
		LEFT JOIN [DW].[DW_DIMTESTPROFICIENCYLEVEL] [DW_DIMTESTPROFICIENCYLEVEL] ON (F.[TESTPROFICIENCYLEVELKEY] = [DW_DIMTESTPROFICIENCYLEVEL].[TESTPROFICIENCYLEVELKEY])
	WHERE TESTTYPE = 'Test_ANet'
	AND TESTSCORETYPE = 'Test'
	--and schoolname_abbreviation = 'NE'
	--AND DIM_S.ENROLLMENTSTATUS = 'Currently Enrolled'
	AND TESTSUBJECT = 'Reading') ANET_READ ON ANET_READ.STUDENTID = S.SYSTEMSTUDENTID AND ANET_READ.RECORD_RANK = 1
WHERE S.ENROLLMENTSTATUS = 'Currently Enrolled'
